### ISSUE TITLE
BUG OrderDetail - ProductID is not being set during order parsing

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-foxy-orders#36]
**Describe the bug**
During Order parsing, ProductID (and maybe OrderID in some cases) are not being set on OrderDetail

**To Reproduce**
1. Complete an order
2. In CMS, check purchased count for product if inventory control is true
3. Number will be `('none')` or will not have increased

**Expected behavior**
Purchased count queries OrderDetail by ProductID, so it returns no results

**Comment by jsirish** [comment]
<img width="1437" alt="Screen Shot 2019-08-07 at 9 48 58 PM" src="https://user-images.githubusercontent.com/1163643/62671614-398ab700-b95d-11e9-9661-d2056852beb3.png">

**Comment by muskie9** [comment]
This has been resolved with the use of `FoxyHelper` and the refactoring of that class.
